source "http://rubygems.org"
gem 'rake', '0.8.7'
gem 'rack-test'
gem 'rspec'
gem 'sinatra'
gem 'resque'
gem 'capybara'
gem 'steak'
gem 'redis'
gem 'resque_unit'        
gem 'i18n'
gem 'machinist', '>= 2.0.0.beta2'
gem 'json'                       
gem 'resque-multi-step', :git => 'git://github.com/Nerian/resque-multi-step.git', :branch => 'update-all', :require => 'resque-multi-step'
gem 'resque-result'